
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
  - "3.8"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment -c conda-forge -c astra-toolbox python=$TRAVIS_PYTHON_VERSION astra-toolbox==1.8 tomopy==1.2.1 pympler==0.9 dxchange==0.1.5 tqdm==4.61.2 matplotlib==3.1.0 coveralls==3.3.1 pytest==6.2.5 pytest-cov=3.0.0 opencv==3.4.2 progressbar ipykernel==5.5.5
  - conda activate test-environment
  - pip install itk==5.2.0.post3
  - pip install itkwidgets==0.32.1

script:
  - pytest --cov=tomosuitepy tests/

notifications:
  email: williamjudge94@gmail.com

after_success:
  - coveralls
